# -*- coding: utf-8 -*-
"""Text to Speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pl02_HHMUR4WrSfzF4uBk2HiF3ljTb1A
"""

def text_to_speech(text, language='en', slow=False):
    """
    Convert text to speech and play it.

    Args:
    text (str): The text to be converted to speech.
    language (str): The language of the text. Defaults to 'en' (English).
    slow (bool): Whether to generate the audio at a slower speed. Defaults to False.

    Returns:
    None
    """
    # Passing the text and language to the engine
    speech = gTTS(text=text, lang=language, slow=slow)

    # Saving the converted audio as a temporary file
    temp_file = "temp_audio.mp3"
    speech.save(temp_file)

    # Loading the audio file
    audio = AudioSegment.from_mp3(temp_file)

    # Playing the audio
    play(audio)

    # Cleanup - delete the temporary file
    os.remove(temp_file)