# -*- coding: utf-8 -*-
"""Speech to Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9RJjKOyfzNJgwoXbmMw7DEkClmPc8DC
"""

def listen_and_recognize(language="en-IN"):
    """
    Listens to audio from the microphone and recognizes speech using Google's Speech Recognition.

    Parameters:
    - language (str): Language code for recognition (default: 'en-IN' for English-India).

    Returns:
    - str: Recognized text if successful, or an error message if recognition fails.
    """
    recognizer = sr.Recognizer()

    with sr.Microphone() as source:
        print("Listening, please say something:")
        audio = recognizer.listen(source)

    try:
        text = recognizer.recognize_google(audio, language=language)
        return text
    except sr.UnknownValueError:
        return "Sorry, I couldn't understand the audio."
    except sr.RequestError as e:
        return f"Could not request results from Google Speech Recognition service; {e}"

